// SPDX-License-Identifier: Apache-2.0

import { snapToGraphemeBoundary } from '@shared/unicode'

/**
 * Streaming Strategy — strategy interface for Telegram Bot streaming message delivery.
 *
 * Abstracts the streaming delivery implementation (sendMessage+editMessageText vs
 * sendMessageDraft) into replaceable strategies, decoupling TelegramBotService's
 * business logic from transport details.
 *
 * Design constraints:
 *   - Strategy instances are owned by TelegramBotService, lifecycle matches the Bot instance
 *   - handleAssistantMessage and handleEvoseProgress share the same strategy instance
 *     (Evose progress and regular streaming reuse the same bubble for the same chatId)
 *   - Strategy is responsible for per-chat state management, throttling, deduplication
 *   - Strategy is NOT responsible for: content formatting, event routing, session management, typing indicator
 */

/**
 * Telegram message text hard limit (characters).
 * The Bot API enforces 0-4096 characters for sendMessage / editMessageText
 * and sendMessageDraft. We use 4000 as a safe ceiling, leaving headroom
 * for potential HTML entity expansion and Unicode edge cases.
 */
export const TELEGRAM_SAFE_TEXT_LIMIT = 4000

/**
 * Truncate content to fit within Telegram's text limit.
 * Appends '…' when truncated so the user can see content was cut.
 */
export function safeContent(content: string): string {
  if (content.length <= TELEGRAM_SAFE_TEXT_LIMIT) return content
  return content.slice(0, snapToGraphemeBoundary(content, TELEGRAM_SAFE_TEXT_LIMIT - 1)) + '…'
}

/** Streaming update parameters */
export interface StreamingUpdateParams {
  /** Telegram chat ID (string type, consistent with upstream) */
  chatId: string
  /** Pre-formatted HTML content (generated by MessageFormatter) */
  content: string
  /** Current session ID (used to generate stop button callback_data) */
  sessionId: string
}

/** Finalization parameters */
export interface FinalizeParams {
  /** Telegram chat ID */
  chatId: string
  /** Final HTML content chunks (may be split into multiple parts due to 4096 char limit) */
  htmlChunks: string[]
}

/**
 * Streaming message delivery strategy.
 *
 * Lifecycle:
 *   sendUpdate()* → finalize() → [release()]
 *   release() can be called at any time for forced cleanup (on session stop/error)
 *
 * Degradation protocol:
 *   sendUpdate() returning false indicates this strategy cannot be used for the current chat;
 *   the caller should switch to the fallback strategy. Once sendUpdate() returns true
 *   (i.e. a bubble has been created), subsequent calls for the same chatId should not
 *   return false (to avoid mid-stream switching that causes duplicate messages).
 */
export interface StreamingStrategy {
  /**
   * Send a streaming update (create or update placeholder bubble).
   *
   * The strategy internally implements throttling and deduplication logic.
   *
   * @returns true  — successfully handled (including throttle-skipped cases)
   *          false — this strategy is not available for the current chat, caller should degrade
   */
  sendUpdate(params: StreamingUpdateParams): Promise<boolean>

  /**
   * Replace the streaming bubble with final formatted content.
   *
   * @returns true  — first chunk has been edit-replaced into the placeholder (caller only sends remaining chunks)
   *          false — strategy could not replace (caller must sendMessage all chunks itself)
   */
  finalize(params: FinalizeParams): Promise<boolean>

  /** Release all streaming state for the specified chatId */
  release(chatId: string): void

  /** Whether the specified chatId has an active streaming bubble */
  hasActive(chatId: string): boolean

  /** Release streaming state for all chats (called when bot stops) */
  releaseAll(): void
}
