// SPDX-License-Identifier: Apache-2.0

import { describe, it, expect } from 'vitest'
import { sanitizeSessionName } from '../../../electron/parsers/sessionNameSanitizer'

describe('sanitizeSessionName', () => {
  // === Skill/Command tags (most frequent) ===

  it('separates command name and user args as structured data', () => {
    const raw = '<command-message>lint.code.quality</command-message> <command-name>/lint.code.quality</command-name> <command-args>Homepage scroll then click button has issues</command-args>'
    expect(sanitizeSessionName(raw)).toEqual({
      text: 'Homepage scroll then click button has issues',
      commandName: '/lint.code.quality',
    })
  })

  it('separates command name with nested content', () => {
    const raw = '<command-message>project.setup</command-message> <command-name>/project.setup</command-name> <command-args> I want to build a pure client app with React + Electron</command-args>'
    expect(sanitizeSessionName(raw)).toEqual({
      text: 'I want to build a pure client app with React + Electron',
      commandName: '/project.setup',
    })
  })

  it('returns null for command without args (pure command invocation)', () => {
    const raw = '<command-message>project.setup</command-message> <command-name>/project.setup</command-name>'
    expect(sanitizeSessionName(raw)).toBeNull()
  })

  it('returns null for command with empty args', () => {
    const raw = '<command-message>foo</command-message> <command-name>/foo</command-name> <command-args>   </command-args>'
    expect(sanitizeSessionName(raw)).toBeNull()
  })

  it('returns null for /clear with command tags (real JSONL format)', () => {
    const raw = '<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>'
    expect(sanitizeSessionName(raw)).toBeNull()
  })

  it('returns commandName as null when command-name tag is missing', () => {
    const raw = '<command-message>foo</command-message> <command-args>do something</command-args>'
    expect(sanitizeSessionName(raw)).toEqual({
      text: 'do something',
      commandName: null,
    })
  })

  // === Skill content injection (system-injected full skill definition) ===

  it('filters skill content injection (Base directory for this skill)', () => {
    const raw = 'Base directory for this skill: /Users/foo/.claude/plugins/cache/superpowers/4.3.1/skills/writing-plans\n\n# Writing Plans\n\n## Overview'
    expect(sanitizeSessionName(raw)).toBeNull()
  })

  it('filters skill invocation instruction (Invoke the … skill)', () => {
    const raw = 'Invoke the superpowers:writing-plans skill and follow it exactly as presented to you'
    expect(sanitizeSessionName(raw)).toBeNull()
  })

  it('filters skill invocation with ARGUMENTS suffix', () => {
    const raw = 'Invoke the superpowers:executing-plans skill and follow it exactly as presented to you\n\nARGUMENTS: Create new branch and start executing.'
    expect(sanitizeSessionName(raw)).toBeNull()
  })

  // === Built-in slash commands ===

  it('filters bare slash commands like /clear', () => {
    expect(sanitizeSessionName('/clear')).toBeNull()
  })

  it('filters /compact command', () => {
    expect(sanitizeSessionName('/compact')).toBeNull()
  })

  it('filters /help command', () => {
    expect(sanitizeSessionName('/help')).toBeNull()
  })

  it('filters slash command with trailing whitespace', () => {
    expect(sanitizeSessionName('/clear  ')).toBeNull()
  })

  it('keeps slash command with arguments as plain text (commandName null)', () => {
    expect(sanitizeSessionName('/commit fix the auth bug')).toEqual({
      text: '/commit fix the auth bug',
      commandName: null,
    })
  })

  // === Context compaction continuation prompt ===

  it('filters context continuation prompt', () => {
    expect(sanitizeSessionName('This session is being continued from a previous conversation that ran out of context.')).toBeNull()
  })

  it('filters continuation prompt with extra text after', () => {
    expect(sanitizeSessionName('This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion.')).toBeNull()
  })

  // === Local command caveat ===

  it('strips local-command-caveat tag entirely', () => {
    const raw = '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond</local-command-caveat>'
    expect(sanitizeSessionName(raw)).toBeNull()
  })

  // === Interruption markers ===

  it('strips [Request interrupted...] markers', () => {
    expect(sanitizeSessionName('[Request interrupted by user for tool use]')).toBeNull()
  })

  it('strips [Error...] markers', () => {
    expect(sanitizeSessionName('[Error: connection timeout]')).toBeNull()
  })

  // === HTML/Markdown tags ===

  it('strips HTML tags from content', () => {
    const raw = '@<Markdown>  Canvas markdown file styling has some issues'
    expect(sanitizeSessionName(raw)).toEqual({
      text: 'Canvas markdown file styling has some issues',
      commandName: null,
    })
  })

  // === Normal content ===

  it('passes through clean text with commandName null', () => {
    expect(sanitizeSessionName('Fix the authentication bug')).toEqual({
      text: 'Fix the authentication bug',
      commandName: null,
    })
  })

  it('trims whitespace', () => {
    expect(sanitizeSessionName('  Hello world  ')).toEqual({
      text: 'Hello world',
      commandName: null,
    })
  })

  it('truncates text to max length', () => {
    const long = 'a'.repeat(200)
    const result = sanitizeSessionName(long)!
    expect(result.text.length).toBeLessThanOrEqual(80)
    expect(result.text.endsWith('…')).toBe(true)
    expect(result.commandName).toBeNull()
  })

  it('returns null for empty string', () => {
    expect(sanitizeSessionName('')).toBeNull()
  })

  it('returns null for whitespace-only', () => {
    expect(sanitizeSessionName('   ')).toBeNull()
  })

  it('normalizes multiple spaces into single space', () => {
    expect(sanitizeSessionName('Fix   the   bug')).toEqual({
      text: 'Fix the bug',
      commandName: null,
    })
  })

  it('collapses newlines into spaces', () => {
    expect(sanitizeSessionName('Fix\nthe\nbug')).toEqual({
      text: 'Fix the bug',
      commandName: null,
    })
  })
})
