// SPDX-License-Identifier: Apache-2.0

import type { AIEngineKind } from '../../../src/shared/types'
import type { ConversationContentBlock } from '../domain/content'

export interface RuntimeTurnUsage {
  readonly inputTokens: number
  readonly outputTokens: number
  readonly cacheReadInputTokens: number
  readonly cacheCreationInputTokens: number
}

export interface RuntimeModelUsage {
  readonly inputTokens: number
  readonly outputTokens: number
  /** Optional provider-reported context window size for this model. */
  readonly contextWindow?: number
  /** Optional provider-reported maximum output tokens for this model. */
  readonly maxOutputTokens?: number
}

/** Session-local turn reference generated by lifecycle adapters. */
export interface RuntimeTurnRef {
  readonly turnSeq: number
}

export type RuntimeDiagnosticSeverity = 'info' | 'warning' | 'error'

export interface RuntimeDiagnosticPayload {
  /** Engine-specific machine-readable code, e.g. "codex.long_thread_compaction_advisory". */
  readonly code: string
  readonly severity: RuntimeDiagnosticSeverity
  readonly message: string
  /** True means runtime must terminate the current turn. */
  readonly terminal: boolean
  /** Optional engine/source hint for observability. */
  readonly source?: string
}

export type RuntimeResultOutcome =
  | 'success'
  | 'max_turns'
  | 'execution_error'
  | 'budget_exceeded'
  | 'structured_output_error'

export interface RuntimeResultPayload {
  readonly outcome: RuntimeResultOutcome
  readonly errors?: string[]
  readonly result?: string
  readonly modelUsage?: Record<string, RuntimeModelUsage>
  readonly costUsd?: number
}

export type RuntimeContextSnapshotConfidence = 'authoritative' | 'estimated'

export interface RuntimeContextSnapshotPayload {
  readonly usedTokens: number
  /**
   * Context window limit in tokens.
   * Null when the adapter does not know the limit (e.g. Claude adapter —
   * the limit arrives separately via modelUsage.contextWindow in turn.result).
   * Null values preserve the previously known limit in ManagedSession.
   */
  readonly limitTokens: number | null
  /** Remaining tokens. Null when limitTokens is unknown. */
  readonly remainingTokens: number | null
  /** Remaining percentage. Null when limitTokens is unknown. */
  readonly remainingPct: number | null
  /** Same-source token telemetry origin, e.g. "codex.token_count". */
  readonly source: string
  readonly confidence: RuntimeContextSnapshotConfidence
  /** Optional provider timestamp; defaults to envelope occurredAtMs when omitted. */
  readonly updatedAtMs?: number
}

export type EngineRuntimeEvent =
  | {
      readonly kind: 'turn.started'
      readonly payload: Record<string, never>
    }
  | {
      readonly kind: 'session.initialized'
      readonly payload: {
        readonly sessionRef?: string
        readonly model?: string
      }
    }
  | {
      readonly kind: 'assistant.partial'
      readonly payload: {
        readonly blocks: ConversationContentBlock[]
      }
    }
  | {
      readonly kind: 'assistant.final'
      readonly payload: {
        readonly blocks: ConversationContentBlock[]
      }
    }
  | {
      readonly kind: 'turn.usage'
      readonly payload: RuntimeTurnUsage
    }
  | {
      readonly kind: 'context.snapshot'
      readonly payload: RuntimeContextSnapshotPayload
    }
  | {
      readonly kind: 'tool.progress'
      readonly payload: {
        readonly toolUseId: string
        readonly chunk: string
      }
    }
  | {
      readonly kind: 'engine.diagnostic'
      readonly payload: RuntimeDiagnosticPayload
    }
  | {
      readonly kind: 'turn.result'
      readonly payload: RuntimeResultPayload
    }
  | {
      readonly kind: 'system.compact_boundary'
      readonly payload: {
        readonly trigger: 'manual' | 'auto'
        readonly preTokens: number
      }
    }
  | {
      readonly kind: 'system.task_started'
      readonly payload: {
        readonly taskId: string
        readonly toolUseId?: string
        readonly description: string
        readonly taskType?: string
      }
    }
  | {
      readonly kind: 'system.task_notification'
      readonly payload: {
        readonly taskId: string
        readonly toolUseId?: string
        readonly status: 'completed' | 'failed' | 'stopped'
        readonly summary: string
        readonly outputFile?: string
        readonly usage?: {
          readonly totalTokens: number
          readonly toolUses: number
          readonly durationMs: number
        }
      }
    }
  | {
      readonly kind: 'system.hook_started'
      readonly payload: {
        readonly hookId: string
        readonly hookName: string
        readonly hookTrigger: string
      }
    }
  | {
      readonly kind: 'system.hook_progress'
      readonly payload: {
        readonly hookId: string
        readonly output: string
      }
    }
  | {
      readonly kind: 'system.hook_response'
      readonly payload: {
        readonly hookId: string
        readonly outcome: 'success' | 'error' | 'cancelled'
        readonly exitCode?: number
        readonly output: string
      }
    }
  | {
      readonly kind: 'protocol.violation'
      readonly payload: {
        readonly reason: string
        readonly rawType?: string
        readonly rawSubtype?: string | null
      }
    }

export interface EngineRuntimeEventEnvelope {
  readonly engine: AIEngineKind
  readonly occurredAtMs: number
  readonly event: EngineRuntimeEvent
  /** Turn-scoped correlation key; omitted for session/global events. */
  readonly turnRef?: RuntimeTurnRef
}

export function createRuntimeEventEnvelope(params: {
  engine: AIEngineKind
  event: EngineRuntimeEvent
  turnRef?: RuntimeTurnRef
  occurredAtMs?: number
}): EngineRuntimeEventEnvelope {
  return {
    engine: params.engine,
    occurredAtMs: params.occurredAtMs ?? Date.now(),
    event: params.event,
    turnRef: params.turnRef,
  }
}

/** True when an event belongs to a specific turn and should carry turnRef. */
export function isTurnScopedRuntimeEventKind(kind: EngineRuntimeEvent['kind']): boolean {
  return (
    kind === 'turn.started' ||
    kind === 'assistant.partial' ||
    kind === 'assistant.final' ||
    kind === 'turn.usage' ||
    kind === 'tool.progress' ||
    kind === 'turn.result' ||
    kind === 'system.compact_boundary' ||
    kind === 'system.task_started' ||
    kind === 'system.task_notification' ||
    kind === 'system.hook_started' ||
    kind === 'system.hook_progress' ||
    kind === 'system.hook_response'
  )
}
